# Generated by Django 3.2 on 2021-04-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '学习', 'verbose_name_plural': '学习'},
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('书', '书'), ('公开课', '公开课'), ('技术演讲', '技术演讲'), ('其他', '其他')], default='其他', max_length=160),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(choices=[('原创', '原创'), ('bilibili', 'bilibili'), ('知乎', '知乎'), ('财新', '财新'), ('技术演讲', '技术演讲'), ('youtube', 'youtube'), ('公开课', '公开课'), ('其他', '其他')], default='原创', max_length=160, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('ARTICLE', 'ARTICLE'), ('ARCHIVE', 'ARCHIVE'), ('STUDY', 'STUDY')], default='ARTICLE', max_length=160, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='slug',
            field=models.SlugField(max_length=160, unique=True, verbose_name='slug'),
        ),
    ]
