# Generated by Django 3.2 on 2021-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='连接名')),
                ('link', models.CharField(max_length=255, verbose_name='连接')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='abstract_markdown',
            field=models.TextField(blank=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_markdown',
            field=models.TextField(blank=True, verbose_name='正文'),
        ),
        migrations.AddField(
            model_name='article',
            name='related_links',
            field=models.ManyToManyField(related_name='_blog_article_related_links_+', to='blog.RelatedLinks'),
        ),
    ]
