# Generated by Django 3.2 on 2021-04-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_markdown',
            field=models.TextField(blank=True, verbose_name='评论'),
        ),
    ]
