# Generated by Django 3.2 on 2021-04-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_relatedlinks_relatedlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedlink',
            options={'verbose_name': '相关链接', 'verbose_name_plural': '相关链接'},
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.uploadedimage')),
            ],
        ),
    ]
