# Generated by Django 3.2 on 2021-04-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_task_review_markdown'),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="StudySubject"
        ),
    ]
