# Generated by Django 3.2 on 2021-04-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210425_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-create_at',), 'verbose_name': '碎碎念', 'verbose_name_plural': '碎碎念'},
        ),
        migrations.AddField(
            model_name='article',
            name='study_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='blog.studysubject', verbose_name='课题'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='公开'),
        ),
    ]
