# deploy.yml
name: "deploy-to-my-server"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install
        working-directory: frontend
      - run: yarn build
        working-directory: frontend
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install -r requirements-base.txt
      - run: touch mysite/settings/.env
      - run: python manage.py collectstatic
        env:
          DJANGO_SETTINGS_MODULE: 'mysite.settings.build'
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY_FOR_BUILD }}
      - run: rm -f mysite/settings/.env
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          ARGS: '-avz'
          TARGET: '/data/aweffr_com_prod'
          EXCLUDE: '/frontend/node_modules'
      - name: restart gunicorn
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup knownhosts
        run: ssh-keyscan aweffr.com >> ~/.ssh/known_hosts
      - name: Run SSH Command
        run: ssh aweffr@aweffr.com "lsof -i:9001 -t | xargs kill -SIGHUP"
